name: build
on: workflow_dispatch

jobs:
  w:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          install: mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-make git

      - uses: actions/checkout@v4

      - run: git clone https://github.com/xmrig/xmrig-deps.git /c/x

      - run: mkdir b && cd b && cmake .. -G "Unix Makefiles" -DXMRIG_DEPS=/c/x/gcc/x64 && make -j2

      - uses: actions/upload-artifact@v4
        with:
          name: xmrig
          path: b/xmrig.exe
