name: Build XMRig Windows Release

on:
  workflow_dispatch:

jobs:
  build_win:
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Setup MSYS2 (UCRT64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >
            mingw-w64-ucrt-x86_64-gcc
            git
            make
            cmake
            mingw-w64-ucrt-x86_64-7zip

      - name: Checkout xmrig
        uses: actions/checkout@v3

      - name: Clone deps
        run: |
          git clone https://github.com/xmrig/xmrig-deps.git
          mv xmrig-deps /c/xmrig-deps

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -G "Unix Makefiles" -DXMRIG_DEPS=/c/xmrig-deps/gcc/x64
          make -j$(nproc)

      - name: Package
        run: |
          cd build
          cp ../src/config.json .
          cp ../bin/WinRing0/WinRing0x64.sys .
          7z a -tzip -mx windows_build.zip xmrig.exe config.json WinRing0x64.sys

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows_build
          path: build/windows_build.zip
